##
## cuRobo robot config for OpenArm right arm
## End-effector: openarm_right_hand_tcp
##
robot_cfg:
  kinematics:
    use_usd_kinematics: False
    urdf_path: "/home/vision/humanoids/openarm/urdf/openarm_bimanual.urdf"
    asset_root_path: "/home/vision/humanoids/openarm/urdf"
    base_link: "openarm_right_link0"
    ee_link: "openarm_right_hand_tcp"
    link_names: null
    collision_link_names: null
    collision_spheres: null
    mesh_link_names: null
    lock_joints: null
    cspace:
      joint_names:
        - "openarm_right_joint1"
        - "openarm_right_joint2"
        - "openarm_right_joint3"
        - "openarm_right_joint4"
        - "openarm_right_joint5"
        - "openarm_right_joint6"
        - "openarm_right_joint7"
      retract_config: [0.0, -1.5708, 0.0, 1.2217, 0.0, 0.0, 0.0]
      null_space_weight: [1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0]
      cspace_distance_weight: [1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0]
      max_jerk: 500.0
      max_acceleration: 12.0
      position_limit_clip: 0.01